### PR TITLE
RD-916 (5.2.0) Add security attributes to all used cookies

### PR DESCRIPTION
**Pull request by qooban**
The same change as in #1257 for 5.2.0.

### CODE REVIEW

**Review by Gelio — APPROVED** [review]

**Comment by qooban** [comment]
We've got problem with `docWidgets` and `docsCheck`. I think we shouldn't update neither `cloudify-ui-components` nor widget's README.md files. I'll try to cheat Jenkins.

**Comment by qooban** [comment]
This is interesting 🙂 

image

Before actual Jenkins job get started we can merge the PR 🙂

**Comment by Gelio** [comment]
> We've got problem with docWidgets and docsCheck. I think we shouldn't update neither cloudify-ui-components nor widget's README.md files. I'll try to cheat Jenkins.

Oh yeah... I guess this: https://github.com/cloudify-cosmo/cloudify-stage/blob/a02903216614ba44d9c747ff2c8c904ec735cf99/scripts/checkDocs.sh#L12-L14

did not work?

**Review by Gelio — APPROVED** [review]

**Comment by qooban** [comment]
> Oh yeah... I guess this: (...) did not work?

Yes, that's one thing. Also, there's no `5.2.0-build` branch on docs repo, so I could not change `DOCS_BRANCH` into anything meaningul.Widget help descriptions were also fetched from `master` branch, so... <ultiple issues here, but I assume we can merge it how it is. 

I'll create ticket(s) to fix it in the future.

**Pull request merged**
