### PR TITLE
RD-2027 Rename widgets files to TS

### PR DESCRIPTION
**Pull request by Gelio**
This PR is very similar to https://github.com/cloudify-cosmo/cloudify-stage/pull/1415 but this time applied to the `widgets` directory. The migration steps were the same as in https://github.com/cloudify-cosmo/cloudify-stage/pull/1415.

Again, I recommend reviewing commit by commit to avoid going through unimportant mechanical changes.

Noteworthy items:
1. I made sure to leave `backend.js` files intact, as they do get special treatment and are not compiled to TS.
2. Many files were not isolated modules (did not import/export anything) so I had to add artificial `export {}`. In those files, I also tried removing the `@ts-nocheck` comment to see if the leftover problems were easy to fix, hence some files may have more changes. The aim was to not introduce functional changes.
    Some of the artificial `export {}` should go away after RD-1609 since we will be using  more ES imports/exports in widgets

There will be one or two additional PRs for `test/jest` and `test/cypress`

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/731/pipeline

Queued 2021-06-08 17:44 CEST

### CODE REVIEW

**Review by qooban — DISMISSED** [review]
Looks good! 

Similarly to #1415 I like that we get some files migrated to TS for free (just by changing the extension).

BTW Are you planning kind of summary at the end of the process? Maybe we can have a counter somewhere exposed to see how many files are there still to be migrated in comparison to the total number of `.ts[x]` files?

**Comment by Gelio** [comment]
> BTW Are you planning kind of summary at the end of the process? Maybe we can have a counter somewhere exposed to see how many files are there still to be migrated in comparison to the total number of .ts[x] files?

I did not plan anything like it initially, but we could definitely do it :smile: Now instead of the ratio of js to ts files we would have to count the ratio of ts files with and without the `@ts-nocheck` comment. Definitely doable, I can even add such a script to the `scripts` directory and maybe we could add it to the weekly guardian's summary to check and report the progress :thinking:

**Comment by Gelio** [comment]
The tests passed aside from the known "getting started" failures, so I will be rebasing after https://github.com/cloudify-cosmo/cloudify-stage/pull/1415 is merged and then working on merging the PR without rerunning the tests again

**Comment by Gelio** [comment]
I have just rebased the PR on top of `master` since #1415 was merged. I did not introduce any code changes.

**Comment by Gelio** [comment]
Now, it's on the latest master (I did not pull `master` before rebasing when I did it a few minutes ago)

**Review by qooban — APPROVED** [review]

**Pull request merged**
