### PR TITLE
RD-3589 Change node-sass to sass (Fix cloudify-stage installation fail on M1 computer)

### PR DESCRIPTION
**Pull request by leon-good-life**
## Description
There is a problem: Can't install cloudify-stage on Apple M1 computer because of node-sass dependency.
I fixed it by changing the sass compiler dependency from `node-sass` to `sass`. The `node-sass` is deprecated according to `node-sass` GitHub Repo Readme: https://github.com/sass/node-sass#node-sass . And this is the common solution suggested on internet and on StackOverflow to my problem: https://stackoverflow.com/questions/68095626/node-sass-with-apple-m1-big-sur-and-arm64 

**Jira ticket:**
https://cloudifysource.atlassian.net/browse/RD-3589

## Screenshots / Videos
Screencast before fix:

https://user-images.githubusercontent.com/17104212/142239921-ab3e344c-6464-42b8-91f8-46d2ba28396a.mov

Screencast after fix:
https://drive.google.com/file/d/1HoUwG2AvYPpAIfQ0D_TRijr5dgA_tR_U/view?usp=sharing

## Checklist

- [x] My code follows the UI Code Style.
- [ ] I verified that all tests and checks have passed.
- [x] I verified if that change requires a documentation update.
- [x] I added proper labels to this PR.

## Tests
System tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1503/pipeline

 

## Documentation
Jira ticket:
https://cloudifysource.atlassian.net/browse/RD-3589

### CODE REVIEW

**Review by qooban — COMMENTED** [review]
System tests passed and it seems reasonable to switch from `node-sass` to `sass`.

Got one comment - when starting stage frontend dev server I see the following warning:
```
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($widthOnHover - $initialWidth, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
84 │             margin: 0 ($horizontalMargin - ($widthOnHover - $initialWidth) / 2);
   │                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    stdin 84:44  root stylesheet
```
Could you fix it at once?

**Comment by leon-good-life** [comment]
@qooban 
The icons in menus look like this:
Screen Shot 2021-11-18 at 10 10 31
I'm not sure if it because of changing `node-sass` to `sass`.

**Comment by qooban** [comment]
> @qooban The icons in menus look like this: Screen Shot 2021-11-18 at 10 10 31 I'm not sure if it because of changing `node-sass` to `sass`.

@leon-good-life Thanks for letting me know. I pulled your branch, installed all the deps and it seems working fine on my end, so maybe something on your side?

**Review by qooban — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
