### PR TITLE
RD-3496 Update version of cloudify-components to 2.9.2

### PR DESCRIPTION
**Pull request by leon-good-life**
## Description
Update `cloudify-ui-components` to version 2.9.2 to fix the audit.
Update `cloudify-blueprint-topology` version.
Update `cloudify-ui-common` version.

## Screenshots / Videos
N/A

## Checklist

- [x] My code follows the UI Code Style.
- [ ] I verified that all tests and checks have passed.
- [x] I verified if that change requires a documentation update.
- [x] I added proper labels to this PR.

## Tests
Updated system tests:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1500/pipeline

 

## Documentation
The following PR updates the docs:
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2029

### CODE REVIEW

**Review by qooban — CHANGES_REQUESTED** [review]
1. Audit is failing, so it seems you need to update versions of more dependencies (`cloudify-ui-common`).
3. Please check system tests. Edit mode failure might not be related to your change, but please verify. If it is not related you can open a bug.
5. Please update PR title to indicate relation with JIRA ticket.

**Review by qooban — COMMENTED** [review]
@leon-good-life Audit is passing with your latest changes, but size limit for the bundle is exceeded. Try to find a solution for that on Sunday. I suggest to compare `cloudify-ui-components` v2.9.0 and v.2.9.2 and see where that increase comes from. I suspect it comes from changing `cloudify-ui-common` from v4.x to v5.x. 

If you won't find the solution, let's discuss it on Monday.

**Comment by leon-good-life** [comment]
@qooban `npm run size` fails in Jenkins:
```
[2021-11-19T08:28:46.616Z] + npm run size
[2021-11-19T08:28:47.619Z] 
[2021-11-19T08:28:47.619Z] > cloudify-stage@6.3.0--.dev1 size /home/jenkins/agent/workspace/cloudify-stage_RD-3496/size
[2021-11-19T08:28:47.619Z] > [ -d "dist" ] && size-limit
[2021-11-19T08:28:47.619Z] 
[2021-11-19T08:28:49.586Z] - Running JS in headless Chrome
[2021-11-19T08:28:58.055Z] ✔ Running JS in headless Chrome
[2021-11-19T08:28:58.055Z]   
[2021-11-19T08:28:58.055Z]   Main JS bundle
[2021-11-19T08:28:58.055Z]   Package size limit has exceeded by 50 B
[2021-11-19T08:28:58.055Z]   Size limit:   354 KB
[2021-11-19T08:28:58.055Z]   Size:         354.05 KB
[2021-11-19T08:28:58.055Z]   Loading time: 7.1 s     on slow 3G
[2021-11-19T08:28:58.055Z]   Running time: 185 ms    on Snapdragon 410
[2021-11-19T08:28:58.055Z]   Total time:   7.3 s
[2021-11-19T08:28:58.055Z]   
[2021-11-19T08:28:58.055Z]   Vendor JS bundle
[2021-11-19T08:28:58.055Z]   Package size limit has exceeded by 281.23 KB
[2021-11-19T08:28:58.055Z]   Size limit:   4.12 MB
[2021-11-19T08:28:58.055Z]   Size:         4.39 MB
[2021-11-19T08:28:58.055Z]   Loading time: 90.1 s  on slow 3G
[2021-11-19T08:28:58.055Z]   Running time: 1.1 s   on Snapdragon 410
[2021-11-19T08:28:58.055Z]   Total time:   91.1 s
[2021-11-19T08:28:58.055Z]   
[2021-11-19T08:28:58.055Z]   Widgets
[2021-11-19T08:28:58.055Z]   Size limit:   3.13 MB
[2021-11-19T08:28:58.055Z]   Size:         3.12 MB
[2021-11-19T08:28:58.055Z]   Loading time: 63.9 s  on slow 3G
[2021-11-19T08:28:58.055Z]   
[2021-11-19T08:28:58.055Z]   Application package
[2021-11-19T08:28:58.055Z]   Package size limit has exceeded by 290.77 KB
[2021-11-19T08:28:58.055Z]   Size limit:   13.74 MB
[2021-11-19T08:28:58.055Z]   Size:         14.02 MB
[2021-11-19T08:28:58.055Z]   Loading time: 287.3 s  on slow 3G
[2021-11-19T08:28:58.055Z]   
[2021-11-19T08:28:58.055Z]   Try to reduce size or increase limit at .size-limit
[2021-11-19T08:28:58.055Z] npm ERR! code ELIFECYCLE
[2021-11-19T08:28:58.055Z] npm ERR! errno 1
[2021-11-19T08:28:58.055Z] npm ERR! cloudify-stage@6.3.0--.dev1 size: `[ -d "dist" ] && size-limit`
[2021-11-19T08:28:58.055Z] npm ERR! Exit status 1
[2021-11-19T08:28:58.055Z] npm ERR! 
[2021-11-19T08:28:58.055Z] npm ERR! Failed at the cloudify-stage@6.3.0--.dev1 size script.
[2021-11-19T08:28:58.055Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2021-11-19T08:28:58.055Z] 
[2021-11-19T08:28:58.055Z] npm ERR! A complete log of this run can be found in:
[2021-11-19T08:28:58.055Z] npm ERR!     /root/.npm/_logs/2021-11-19T08_28_57_967Z-debug.log
script returned exit code 1
```
How can I fix that?

**Comment by qooban** [comment]
> How can I fix that?

@leon-good-life Try to find solution on your own and we'll see on Monday. See my [previous comment](https://github.com/cloudify-cosmo/cloudify-stage/pull/1668#pullrequestreview-810993492).

**Comment by leon-good-life** [comment]
@qooban I tried to compare the build size of the versions of cloudify-ui-components. I was not sure if I do it correctly. I saw that the build script creates "se" directory. So, I built both master and v2.9.0. I used `du -sh` to view the "se" directory size. Both in `v2.9.0` and in `master` the size is `628K`.
```
leon@Leons-MacBook-Pro cloudify-ui-components % git checkout tags/v2.9.0 -b v2.9.0
Switched to a new branch 'v2.9.0'
leon@Leons-MacBook-Pro cloudify-ui-components % git log
commit 1402810845e1d4691239cc96bc4e484c5667884e (HEAD -> v2.9.0, tag: v2.9.0)
Author: Jakub Madej <jakub.madej@cloudify.co>
Date:   Tue Oct 12 14:40:23 2021 +0200

    Bump version to v2.9.0

commit ea5b970e6cc5b7cce0009f39b04c398356401ecf
Author: kubama <jakub.madej@amartus.com>
Date:   Tue Oct 12 13:15:08 2021 +0200

    RD-3241 Enhanced `EditableLabel` component (#88)

commit 818836cc27e077e47e52f2fac8e9b1c9a44cdb82 (tag: v2.8.1)
Author: Jakub Niezgoda <jakub.niezgoda@amartus.com>
Date:   Mon Oct 11 07:40:02 2021 +0200

    Bump version to v2.8.1

commit 5341bcbd296090adb9f1e2e5db0645cfc089adf9
Author: Jakub Niezgoda <jakub.niezgoda@nitarch.pl>
Date:   Mon Oct 11 07:38:55 2021 +0200

    RD-3290 Fix security audit issue coming from `prismjs` package version (#87)
    
    * Apply automatic `npm audit` fix
    * Fix TS errors coming from lack of declaration file for module 'react-color'
    * Fix package-lock.json by running `npm install`

commit 5c244e0c9f701484cc230b93d5e5418993de3a20
Author: Jakub Niezgoda <jakub.niezgoda@nitarch.pl>
Date:   Fri Sep 17 12:42:04 2021 +0200

leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % rm -rf es
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % npm run build

> cloudify-ui-components@2.9.0 build /Users/leon/cloudify-ui-components
> bash scripts/build-components.sh && npm run generate-type-declarations

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Successfully compiled 158 files with Babel (13868ms).

> cloudify-ui-components@2.9.0 generate-type-declarations /Users/leon/cloudify-ui-components
> tsc -b src

leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % du -sh es
628K	es
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % git log
commit f15b901bf2de43c925650c0d02ead3e08ea312c5 (HEAD -> master, origin/master, origin/HEAD)
Author: Leon Gilyadov <leon.good.life@gmail.com>
Date:   Fri Nov 19 23:12:10 2021 +0200

    Change node-sass to sass (#102)
    
    Co-authored-by: Leon Gilyadov <leon@Leons-MacBook-Pro.local>
    Co-authored-by: Jakub Niezgoda <jakub.niezgoda@nitarch.pl>

commit 6afcb8f7efa95208f2224b3f828502c2abef8a50
Author: Jakub Niezgoda <jakub.niezgoda@nitarch.pl>
Date:   Fri Nov 19 06:23:21 2021 +0100

    RD-3591 Fix reference images used for loki visual tests after Google Chrome update (#103)

commit 6d74fe4256d394136bb40afcc1e0eb194f5ad178 (tag: v2.9.2)
Author: Jakub Niezgoda <jakub.niezgoda@amartus.com>
Date:   Tue Nov 16 14:50:05 2021 +0100

    Bump version to v2.9.2

commit 7a01bb8c688b7cab7f9c2aa9304484d79f19fa49
Author: Leon Gilyadov <leon.good.life@gmail.com>
Date:   Mon Nov 15 16:25:48 2021 +0200

    RD-3496 Fix audit, Revert commit 0572d8a (#99)

commit 17bb8687a7ac3b1b9e22a768d85b616bf8f98c0b
Author: Yuval Rapaport <53003755+yuvlar@users.noreply.github.com>
Date:   Mon Nov 15 15:09:36 2021 +0200

    RD-1766 refactor pipeline, parallel tests and add caching (#98)
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % rm -rf es             
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % npm run build         

> cloudify-ui-components@2.9.2 build /Users/leon/cloudify-ui-components
> bash scripts/build-components.sh && npm run generate-type-declarations

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Successfully compiled 158 files with Babel (2875ms).

> cloudify-ui-components@2.9.2 generate-type-declarations /Users/leon/cloudify-ui-components
> tsc -b src

leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % 
leon@Leons-MacBook-Pro cloudify-ui-components % du -sh es             
628K	es
```

**Review by qooban — DISMISSED** [review]

**Pull request merged**
