### PR TITLE
RD-3981 Changed fields order in terraform modal

### PR DESCRIPTION
**Pull request by kubama**
## Description
Changed fields order in terraform modal

## Screenshots / Videos
image

## Checklist

- [X] My code follows the UI Code Style.
- [x] I verified that all tests and checks have passed.
- [X] I verified if that change requires a documentation update.
- [X] I added proper labels to this PR.

## Tests
Just changed order of fields in the view, not planning system tests execution.

 

## Documentation
N/A

### CODE REVIEW

**Review by qooban — COMMENTED** [review]
I personally don't like the idea of changing that fields order. See my comment in RD-3981 for reasoning. Until it is fully confirmed that it is the right way to go, I'm not approving this PR.

**Review by qooban — COMMENTED** [review]
I personally don't like the idea of changing that fields order. See my comment in RD-3981 for reasoning. Until it is fully confirmed that it is the right way to go, I'm not approving this PR.

**Comment by kubama** [comment]
IIUC it was confirmed (see @alexmolev's comment to RD-3981). I'm re-requesting a review as the ticket is in the current sprint.

**Review by qooban — COMMENTED** [review]
> IIUC it was confirmed (see @alexmolev's comment to [RD-3981](https://cloudifysource.atlassian.net/browse/RD-3981)). I'm re-requesting a review as the ticket is in the current sprint.

I've added one more comment in RD-3981 with a suggestion to solve the problem in a different way. If possible, let's wait for the answer in RD-3981 before merging (that means - maybe until the next week when Alex is back).

**Comment by qooban** [comment]
@kubama I guess you can close this PR as the change was implemented as part of #1930, am I right?

**Pull request closed without merging**
