### PR TITLE
RD-3487: Modify checkbox styling

### PR DESCRIPTION
**Pull request by Vorbert-Kruk**
## Description

Changes consisting of using a different set of LESS variables and styling rules to adjust the default SUIR checkbox styling, along with it's variations

### Before
Before

### After
After

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests

 

N/A

## Documentation

N/A

### CODE REVIEW

**Review by qooban — APPROVED** [review]
Looks good! 👍🏻 

What happened to `backend/package-lock.json`? 🤔

**Comment by qooban** [comment]
@Vorbert-Kruk If you are wondering why CI seems to be blocked, I suspect that cherry-picking this one https://github.com/cloudify-cosmo/cloudify-stage/pull/2172 could help.

**Comment by Vorbert-Kruk** [comment]
> Looks good! 👍🏻
> 
> What happened to `backend/package-lock.json`? 🤔

Probably it appeared due to switching between `master` and current branch, nicely spotted!
I've removed those modifications 🎸

**Comment by qooban** [comment]
Now it seems like you've been hit by RD-5947.
Workaround is here #2184 🙂

**Pull request merged**
