### PR TITLE
RD-1982: Remove unnecessary page list reversing

### PR DESCRIPTION
**Pull request by NorbertAmartus**
## Description

Changes consists of removing unnecessary reversing of the page list, which comes with a little bit of refactoring 😁 
Additionally, I've managed to use explicit imports for the `lodash` methods (like `isEmpty`) and used native JS array methods for some operations as they're favoured by our [UI code style guideliness](https://cloudifysource.atlassian.net/wiki/spaces/RD/pages/435388492/UI+Code+Style#SHOULD:-Use-built-in-JS-functions-instead-of-utilities-functions-from-external-packages)

## Screenshots / Videos

N/A

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I verified that all tests and checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests

 

Due to the [mentioned System Sest issues](https://cloudify.slack.com/archives/G9MN0TDG8/p1651046286663119) I'll execute them after [this task](https://cloudifysource.atlassian.net/browse/RD-4787) will be delivered (as without it, executing System Tests will result in getting a failure status)

I've did a manual test and everything seems to working as expected 🎉

## Documentation

N/A

### CODE REVIEW

**Comment by NorbertAmartus** [comment]
Due to the [mentioned System Sest issues](https://cloudify.slack.com/archives/G9MN0TDG8/p1651046286663119) I'll execute them while after [this task](https://cloudifysource.atlassian.net/browse/RD-4787) will be delivered (as without it, executing System Tests will result in getting an error)

**Review by qooban — APPROVED** [review]
LGTM 👍🏻 

As you have mentioned that you have manually tested we should be good to merge it.
Optionally you can wait until RD-4787 will be solved.

I assume that [these changes](https://github.com/cloudify-cosmo/cloudify-stage/pull/1943/files#diff-d021eed48648d7bb505778546a9acf0c14084bec4435a9714ac9b6b7da0008e4) won't be relevant any more or am I missing something? FYI @jawamartus

**Review by jawamartus — APPROVED** [review]
כל הכבוד!
It's mean - Well done!

**Comment by jawamartus** [comment]
>It's mean - Well done
כל הכבוד!


That's example how I guess every editor would fail when you would use RTL and LTR texts in one input. Even at github.

**Comment by NorbertAmartus** [comment]
Thanks for the review and for the language curios! 🎉 
I don't know how to properly pronounce them yet, but I'll learn how to do so with the help of google translator 😄

**Comment by NorbertAmartus** [comment]
>As you have mentioned that you have manually tested we should be good to merge it.
Optionally you can wait until [RD-4787](https://cloudifysource.atlassian.net/browse/RD-4787) will be solved.

In that case, I'll merge this PR, because we don't know how much we would need to wait for [RD-4787](https://cloudifysource.atlassian.net/browse/RD-4787) to be resolved

**Pull request merged**
