### PR TITLE
RD-3734 - Transforming links which are pointing out to the local MD file

### PR DESCRIPTION
**Pull request by NorbertAmartus**
## Description

To this moment, links (which were pointing out to the currently viewed documentation file) weren't working properly while they were displayed inside the application (not the documentation page)
This PR contains modifications will resolve this issue 🎉 

## Screenshots / Videos

N/A

## Checklist

- [x] My code follows the UI Code Style.
- [ ] I verified that all tests and checks have passed.
- [x] I verified if that change requires a documentation update.
- [x] I added proper labels to this PR.

## Tests

 

I've recreated the problem (mentioned inside the corresponding ticket) and problem doesn't appear anymore 🎉 

## Documentation

N/A

### CODE REVIEW

**Review by qooban — APPROVED** [review]
Well done 👍🏻 

1. Seems like size limit for widgets needs to be updated.
2. In the next PRs related to widgets help description you may consider migrating `updateReadmes.js` to TS.

**Comment by NorbertAmartus** [comment]
@qooban 
> 1. Seems like size limit for widgets needs to be updated.

Oh, you're right!
I'm adjusting it right away!

> 2. In the next PRs related to widgets' help fixes you may consider migrating `updateReadmes.js` to TS 🙂
Hmm it may be an idea 💪 
When it comes to this kind of modifications, we could also replace the `request` library (which is the only instance, that relates to the `<rootDir>/package.json` 😎 )

And for that, we could create a ticket, on progressing which I'd migrate this file to typescript 😁 
Let me know what you think about this idea 😉

**Review by qooban — APPROVED** [review]
> And for that, we could create a ticket, on progressing which I'd migrate this file to typescript grin
Let me know what you think about this idea wink

Yesterday I was creating sub-tasks for RD-382 and one of them is RD-3803 (which is about migrating CI scripts, which means `updateReadmes.js` 🙂).

**Comment by NorbertAmartus** [comment]
> > And for that, we could create a ticket, on progressing which I'd migrate this file to typescript grin
> > Let me know what you think about this idea wink
> 
> Yesterday I was creating sub-tasks for [RD-382](https://cloudifysource.atlassian.net/browse/RD-382) and one of them is [RD-3803](https://cloudifysource.atlassian.net/browse/RD-3803) (which is about migrating CI scripts, which means `updateReadmes.js` 🙂).

Oh, as always, when it comes to the jira tickets, you're 10 steps ahead 😁 
So I think, that taking this task would be a perfect opportunity, to migrate this file to ts 😎

**Pull request merged**
