### PR TITLE
RD-2600 Disable failing topology test

### PR DESCRIPTION
**Pull request by Gelio**
That test failed in https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/753/tests/ so according to our new rules, I am disabling it.

I have added RD-2600 to the next sprint.

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/754/pipeline

Queued 2021-06-11 13:46 CEST

### CODE REVIEW

**Review by qooban — APPROVED** [review]

**Comment by Gelio** [comment]
I see that another test in `topology_spec` failed :worried: I will investigate it on Monday

**Comment by qooban** [comment]
> I see that another test in topology_spec failed worried I will investigate it on Monday

That's crazy. What wrong this week 😕 
Bad biometeorological conditions in the Jenkins cloud? ;-)

And regarding the issue with Topology spec - I tried to reproduce it locally (with the latest Cloudify Manager) - all tests are passing 😕

**Comment by Gelio** [comment]
Yeah, Jenkins seems to be having a bad week :smile: 

Here's a rerun for this branch to check if the test that failed in the previous run (https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/754/pipeline) fails again:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/763/pipeline

If yes, I will disable it too and add a new bug for it. If not, I will assume it was a one-off and just merge the PR

**Comment by Gelio** [comment]
I have no clue why the test `allows to expand component node` failed again in https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/763/pipeline as it is passing on master and I don't see any dependency between the test I disabled and `allows to expand component node`. There is some error when rendering the widget, but I have no clue what it is:
image


Thus, I will merge this PR as-is, and only skip the one that has been failing before.

To be fair, though, when running the whole `topology_spec` locally I don't encounter any errors :confused:

**Pull request merged**
