### PR TITLE
RD-3876 #1813 merge to 6.3.1

### PR DESCRIPTION
**Pull request by kubama**

### CODE REVIEW

**Comment by kubama** [comment]
@qooban Do you think we should merge https://github.com/cloudify-cosmo/cloudify-stage/commit/8a0f97e1b099a3204baeae73d35183c21833a628 to satisfy docCheck?

**Review by qooban — APPROVED** [review]
Looks good 👍🏻 

Could you verify that all system tests are passing on `6.3.1-build` branch after merge?

**Comment by kubama** [comment]
> Could you verify that all system tests are passing on `6.3.1-build` branch after merge?

Sure, will do.

**Comment by kubama** [comment]
@qooban 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/2096/
All good except one failure that is present on master too.

**Comment by qooban** [comment]
@kubama Thanks for verification 👍🏻 

However, weems like you executed it on `master` branch of cloudify-manager, so probably during the tests `6.4.0-dev` image was used. Possibly we'll be doing more tests before `6.3.1` releases anyway, but maybe worth to double check if with both `BRANCH` and `STAGE_BRANCH` set to `6.3.1-build` everything is fine. Probably Filters widget spec won't fail there as Filters API changes are not part of 6.3.1.

**Comment by kubama** [comment]
> However, weems like you executed it on `master` branch of cloudify-manager, so probably during the tests `6.4.0-dev` image was used. Possibly we'll be doing more tests before `6.3.1` releases anyway, but maybe worth to double check if with both `BRANCH` and `STAGE_BRANCH` set to `6.3.1-build` everything is fine. Probably Filters widget spec won't fail there as Filters API changes are not part of 6.3.1.

https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/2100/

**Pull request merged**
