### PR TITLE
RD-1247 Update cloudify-ui-components; Move info button after required indicator in form inputs

### PR DESCRIPTION
**Pull request by leon-good-life**
## Description
Update cloudify-ui-components; Move info button after required indicator in form inputs

[Jira ticket: RD-1247](https://cloudifysource.atlassian.net/browse/RD-1247)
[PR in Cloudify-Components: #133](https://github.com/cloudify-cosmo/cloudify-ui-components/pull/133)

## Screenshots / Videos
Screen Shot 2022-05-31 at 11 52 17

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2821/pipeline

 

## Documentation
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2229

### CODE REVIEW

**Comment by leon-good-life** [comment]
TODO: check package-lock.json

**Comment by leon-good-life** [comment]
I ran `git stash`, `git checkout master`, `npm ci`. Then `npm install Cloudify-ui-components`, Here is the `package-lock.json`:
https://user-images.githubusercontent.com/17104212/171144637-d2af595b-c708-4674-bc7e-a44cd6d9398d.mov

**Comment by leon-good-life** [comment]
I reverted my changes locally without using git revert. Then I installed again Cloudify-ui-components. The package-lock.json is smaller now.

**Comment by leon-good-life** [comment]
I started again system tests: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2823/pipeline

In previous system tests only `edit_mode_spec`, other tests fails also in master branch.

**Review by qooban — COMMENTED** [review]
I think `package-lock.json` change can even be smaller and more accurate.

See https://github.com/cloudify-cosmo/cloudify-stage/compare/master...RD-1247-qooban

You can cherry-pick my commit - efed8ee9bd63104f4468f4379e8c4b7f75661384

**Review by qooban — APPROVED** [review]

**Pull request merged**
