### PR TITLE
RD-2575 Upgrade cloudify packages

### PR DESCRIPTION
**Pull request by Gelio**
The changes are identical to https://github.com/cloudify-cosmo/cloudify-blueprint-composer/pull/902, so refer to that PR for the description of the changes :smile: 

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/750/pipeline

Queued at 2021-06-10 15:07 CEST

### CODE REVIEW

**Review by qooban — APPROVED** [review]
Looks good!

**Comment by Gelio** [comment]
Just `widgets/filter_spec` failing in the system tests. Looks like it's just changing the version of `components` in the docs and we're good to go with this PR

https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1876

**Comment by qooban** [comment]
I merged https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1876 and restarted CI here: [cloudify-stage - RD-2575-upgrade-cloudify-packages #2](https://jenkins.cloudify.co/blue/organizations/jenkins/cloudify-stage/detail/RD-2575-upgrade-cloudify-packages/2/pipeline), so you can merge it once it passes.

**Comment by Gelio** [comment]
Great, thank you!

**Pull request merged**
