### PR TITLE
RD-5205 part 1: make headers consistent in events widget

### PR DESCRIPTION
**Pull request by leon-good-life**
## Description
Part 1 of RD-5205

## Screenshots / Videos
Screen Shot 2022-07-13 at 15 04 34

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3116/pipeline

 

## Documentation
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2246

### CODE REVIEW

**Comment by leon-good-life** [comment]
I started system tests: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3116/pipeline

**Review by qooban — COMMENTED** [review]
Code changes looks good.

Tests - seems like you need to re-run the job as it failed (looks like env issue).
Documentation - are you planning to update it at once?

**Comment by leon-good-life** [comment]
I started `events_spec` on Jenkins:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3121/pipeline

**Comment by leon-good-life** [comment]
I updated docs repo: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2246

**Comment by leon-good-life** [comment]
`events_spec` passed in Jenkins.

**Pull request merged**
