### PR TITLE
RD-1075 Refactored widget backend doX API

### PR DESCRIPTION
**Pull request by kubama**
This PR addresses https://github.com/cloudify-cosmo/cloudify-stage/pull/1402#pullrequestreview-673812686 (point 2)

System tests: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/705/

### CODE REVIEW

**Review by Gelio — COMMENTED** [review]
I don't have any comments, but I am not fully confident in my review :smile: I only scanned the changes and they made sense, but I did not read each change with great detail

**Review by qooban — DISMISSED** [review]
LGTM 👍🏻

**Comment by kubama** [comment]
Scheduled another system tests execution as the previous one hung up: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/707/

**Review by qooban — APPROVED** [review]

**Review by Gelio — APPROVED** [review]

**Comment by kubama** [comment]
`blueprint_sources_spec` started to fail on this branch. I provided a fix, however I don't see any direct correlation with this PR.

**Review by qooban — APPROVED** [review]

**Review by Gelio — APPROVED** [review]
> `blueprint_sources_spec` started to fail on this branch. I provided a fix, however I don't see any direct correlation with this PR.

There's been some shady stuff going on last week with many tests starting to fail out of the blue. This may be a continuation of that process :smile:

**Pull request merged**
