### PR TITLE
RND-96 Add HELM chart wrapper frontend

### PR DESCRIPTION
**Pull request by kubama**
## Description
Added HELM chart wrapper frontend

## Screenshots / Videos
image

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4718/ - pass

 

## Documentation
Separate ticket

### CODE REVIEW

**Comment by qooban** [comment]
I'll review it tomorrow morning.

**Review by qooban — APPROVED** [review]
LGTM 👍🏻 

(FYI Minor thing - I updated PR title: RD-96 -> RND-96)

**Comment by kubama** [comment]
> (FYI Minor thing - I updated PR title: [RD-96](https://cloudifysource.atlassian.net/browse/RD-96) -> RND-96)

I have to align my habits :)

**Comment by kubama** [comment]
As I didn't get review from @Blewin for over 24h I'm merging this PR with single approval.

**Pull request merged**
