### PR TITLE
RD-2027 Finalize renaming files to TS

### PR DESCRIPTION
**Pull request by Gelio**
This PR disables importing JS files in TS files, which is some automation to prevent us from going back to JS :smile: 

Besides, I have added a script for calculating how many JS/TS/fully migrated TS files are there in the repo.

I have created https://docs.google.com/spreadsheets/d/1pDXaJHCUZWTYbhoHl9pc07VdRwre85Yx7OoRH9xtLzg/edit#gid=0 to track it over time.

## System tests

The only changes are TS config, so if `npm run check-types` passes in Multibranch CI, the PR is good to go. There is no need for full tests.

Just to be sure, I'll run them on Monday, as the logs will probably be erased anyway over the weekend.

### CODE REVIEW

**Comment by qooban** [comment]
Won't be able to review it today, I'll review it on Monday.

**Review by qooban — APPROVED** [review]
Code looks good!

The chart in the spreadsheet also looks good. Seems like the migration pace is ~25%. Nice. Of course we need to be aware that we added a lot of new code in which TS was used from the beginning.

If I understand correctly it takes into account `backend` folder, but we don't have TS support there yet. Right? I'm just wondering what is the migration status in the FE part?

**Comment by Gelio** [comment]
> If I understand correctly it takes into account `backend` folder, but we don't have TS support there yet. Right? I'm just wondering what is the migration status in the FE part?

Yup, that's correct. The `backend` folder only contains JS files, so the 98 files come from there. All other files come from the frontend folders :slightly_smiling_face: I believe this is sufficient to track the migration, but let me know if you'd rather have a strict split between frontend and backend

**Comment by qooban** [comment]
> I believe this is sufficient to track the migration, but let me know if you'd rather have a strict split between frontend and backend

It's perfectly fine. No need to change it.

**Comment by Gelio** [comment]
Great, I will move onto merging this PR in this case :slightly_smiling_face:

**Pull request merged**
