### PR TITLE
RD-2594 Remove tours from UI

### PR DESCRIPTION
**Pull request by Gelio**
Remove all code related to tours from the UI application and the backend.

Ripgrep results for `tour`:

```sh
15:39 $ rg tour
doc/diagrams/architecture-backend.txt
5:[ExpressJS Web Server|server.js]->[Routes|folder: &#47;routes|Applications;URL: &#47;applications|Auth;URL: &#47;auth|BlueprintAdditions;URL: &#47;ba|BlueprintUserData;URL: &#47;bud|ClientConfig;URL: &#47;config|External;URL: &#47;external|File;URL: &#47;file|GitHub;URL: &#47;github|Plugins;URL: &#47;plugins|ServerProxy;URL: &#47;sp|SourceBrowser;URL: &#47;source|Style;URL: &#47;style|Templates;URL: &#47;templates|Tours;URL: &#47;tours|UserApp;URL: &#47;ua|WidgetBackend;URL: &#47;wb|Widgets;URL: &#47;widgets]
```

Meaning the only file that remains with something related to `tour` is https://github.com/cloudify-cosmo/cloudify-stage/blob/RD-2594-6.1-remove-tours-from-UI/doc/diagrams/architecture-backend.txt (I have no clue about the format used there, so I don't know how to modify it safely)

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/858/pipeline

Queued 2021-06-28 15:40 CEST

### CODE REVIEW

**Comment by kubama** [comment]
Nothing to be removed from `package.json`?

**Comment by Gelio** [comment]
> Nothing to be removed from `package.json`?

Yeah, good point :+1: I'll revisit it tomorrow

**Comment by Gelio** [comment]
@kubama I have taken a look at the imports in the code that I removed and it looks like `hopscotch` is no longer required. I removed all occurrences of hopscotch and related resources that I found. I did not find any other candidates to be removed :slightly_smiling_face:

**Comment by Gelio** [comment]
I cannot request a re-review :slightly_smiling_face: @kubama could you review again?

**Review by kubama — DISMISSED** [review]
Looks good - approving.

Optional: I have noticed application package size dropped down by 7.5KB - you may consider lowering the limit in this case, although I'm not sure it's worth it 🙂.

**Comment by Gelio** [comment]
> Optional: I have noticed application package size dropped down by 7.5KB - you may consider lowering the limit in this case, although I'm not sure it's worth it .

Sure, let's do it :smile: I'll lower the values a bit

**Review by kubama — APPROVED** [review]

**Review by stepek — APPROVED** [review]
LGTM!

**Pull request merged**
