### PR TITLE
RD-2032 Refetch deployments on deployments:refresh

### PR DESCRIPTION
**Pull request by Gelio**
Refetch the deployments in Deployments View on the `deployments:refresh` event.

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/438/pipeline

Ran 2021-04-13 11:56 CEST

### CODE REVIEW

**Review by kubama — DISMISSED** [review]

**Review by qooban — APPROVED** [review]
LGTM 👍🏻

**Comment by Gelio** [comment]
I've rebased the PR on master as #1303 was merged :slightly_smiling_face: 

System tests: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/438/pipeline

**Review by kubama — APPROVED** [review]

**Review by qooban — APPROVED** [review]

**Comment by Gelio** [comment]
The `agents_spec` in https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/438/pipeline failed. This seems weird, as I did not touch that code in any way and I don't see a connection.

The `agents_spec` is passing for me locally:
image

I'd rather not rerun the tests here and block the pipeline for 1h to verify a possible flake

@qooban @kubama Are you ok with merging the PR in this circumstance?

**Comment by kubama** [comment]
> Are you ok with merging the PR in this circumstance?

I'm OK.

**Comment by qooban** [comment]
> I'd rather not rerun the tests here and block the pipeline for 1h to verify a possible flake
> Are you ok with merging the PR in this circumstance?

Yep, I'm OK, too.

Can we have a JIRA issue for that flaky test? (of course with `CI` & `UI` labels)

**Comment by Gelio** [comment]
> Can we have a JIRA issue for that flaky test? (of course with `CI` & `UI` labels)

Sure: RD-2039 :slightly_smiling_face: 

---

I'll merge this PR, then

**Pull request merged**
