### PR TITLE
RD-3584 Modified the layout of the dashboard

### PR DESCRIPTION
**Pull request by NorbertAmartus**
## Description

Changes bringed with this PR will modify the layout of the dashboard, so that the `execution` and `executionsStatus`  widgets would fill all the available horizontal space   
Additionally, some amount of the comments (related to the creator of the files) has been removed, due to the [ongoing refactors](https://cloudifysource.atlassian.net/wiki/spaces/RD/pages/2148073473/Ongoing+Refactors+in+Cloudify+UI#Migrating-files-to-TypeScript)

### Before
before

### After
after

## Checklist

- [x] My code follows the UI Code Style.
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires a documentation update.
- [x] I added proper labels to this PR.

## Tests

 

Locally I've run all tests related to the modified widget (the only test related to them was stored in `executions_spec.ts` file) and additionally I've run `npm run test:frontend` command, which has passed succesfully
Moreover, I've run the [System Tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1589)

### CODE REVIEW

**Review by qooban — COMMENTED** [review]
@NorbertAmartus It seems that you need to update your branch and check/re-run system tests (there are some failures). I'll re-review once they pass.

I don't have strict opinion here, but have gut feeling that we shouldn't put big amount of unrelated refactorings into such small PR. Maybe it should be part of a separate PR? (as you have already done it, so you can cherry-pick the commit) BTW Are there any remaining comments? @kubama What do you think?

**Comment by kubama** [comment]
> @kubama What do you think?

Yes, I agree. For ongoing refactors we should only address files related to the actual change. Since the refactor in ongoing anybody touching a file is supposed to do the change (here - remove author comment) anyway, so there is no real benefit in doing it upfront.
Here, the git log entry will be a bit misleading, as without going into details and checking all diffs it won't be clear which files needed to be updated to accomplish the ticket.

**Comment by NorbertAmartus** [comment]
Provided arguments are more than enough to discourage me from duplicating this behaviour in the future 😁
I've removed commit in order to keep the modifications related to the task itself.

I may have an additional question related to internal refactors, but I'll ask it on the slack channel

**Comment by NorbertAmartus** [comment]
> @NorbertAmartus It seems that you need to update your branch and check/re-run system tests (there are some failures). I'll re-review once they pass.

I've run again the [system tests](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1589/pipeline/55/) and to my surprise, the tests were failing in scenarios, which are not related to the work that I've done

I've executed same test file, which is failing, on the master branch and the problem seems to appear here.

I've created [this bug](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1589/pipeline/55/) and inform the current UI guardian about that issue.

**Review by qooban — APPROVED** [review]
Looks good 👍🏻 

Thanks for taking care of system tests and submitting an issue in JIRA.

**Pull request merged**
