### PR TITLE
RD-2372 Prevent Execution Task Graph crashing when no deployment

### PR DESCRIPTION
**Pull request by Gelio**
When the deployment was being deleted, the component crashed and did not recover when changing the selected deployment. Having an explicit error check prevents the widget from crashing.

## Video

https://user-images.githubusercontent.com/889383/118945695-fb099500-b955-11eb-8d42-f6611d9b6012.mp4

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/628/pipeline

Queued 2021-05-20 17:52 CEST

### CODE REVIEW

**Comment by Gelio** [comment]
I've force pushed to restart the CI jobs

**Review by qooban — APPROVED** [review]
LGTM 👍🏻

**Review by kubama — APPROVED** [review]

**Comment by Gelio** [comment]
The tests did not run in the end. Here's a new run:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/624/pipeline

**Comment by Gelio** [comment]
FYI I have reported RD-2412 to revisit the issue in 6.1 (Ofer's request)

**Comment by Gelio** [comment]
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/624/pipeline/56 failed with an `InterruptedException`. I am going to schedule another rerun of the pipeline. If it fails, I will only run deployment view spec locally and merge the PR if it passes, as I don't want to waste more time on CI retries.

The rerun:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/628/pipeline

**Comment by Gelio** [comment]
The errors that happened in https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/628/tests do not seem to be related to this PR:
1. Known error for bulk actions in Deployments View
2. Errors in Getting Started are probably coming from #1353 

With that, I am merging the PR :slightly_smiling_face:

**Pull request merged**
