### PR TITLE
RD-2003 Display the number of only immediate subdeployments

### PR DESCRIPTION
**Pull request by Gelio**
Show the correct numbers in the drill-down buttons in Deployments View.

## Screenshot

image

Notice that the number of subservices in the drill-down button is 1, meaning that it correctly counts only the immediate children. The table still shows 3 subservices, as it counts all ancestors.

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/449/pipeline

Ran 2021-04-13 15:57 CEST

### CODE REVIEW

**Review by kubama — APPROVED** [review]

**Comment by Gelio** [comment]
I've rebased the PR on the base branch, but it's still waiting for #1305 to be merged first

**Review by qooban — COMMENTED** [review]
I've got one general comment about naming consistency.

Backend endpoint fields - snake-cased - `sub_environments*`/`sub_services*` suggests to be mapped to `subEnvironments*`/`subServices*`. You use `subenvironments*`/`subservices*`. Is that intentional? Is it because in natural language it's one word? If so, then maybe on the backend side it should be fixed?

**Comment by Gelio** [comment]
> Backend endpoint fields - snake-cased - `sub_environments*`/`sub_services*` suggests to be mapped to `subEnvironments*`/`subServices*`. You use `subenvironments*`/`subservices*`. Is that intentional? Is it because in natural language it's one word? If so, then maybe on the backend side it should be fixed?

I'm not sure. _Subenvironments_ sounds natural to me, as a single word. I would not write that as 2 words, _sub environment_, the way the backend fields suggest :slightly_smiling_face: Is that a blocker (hence no approval, only a comment)?

I see more problems than benefits from doing this change (yes, we then use correct English, but we have to synchronize the naming change between the frontend and the backend to get the functionality to keep working) - IMO, the cons outweigh the pros here :slightly_smiling_face: 

---

The system tests failed only due to test coverage, so I'm looking for approvals before I merge the PR

**Review by qooban — APPROVED** [review]
👍🏻 

Reg. naming - that was not a blocker at all, I was just curious about it. 
I agree that it is something to discuss with Mohammed probably.

**Comment by Gelio** [comment]
No code changed since @kubama's approval (I've only rebased because the base branch was merged to master), so I assume that the approval still stands :slightly_smiling_face: Thus, with 2 approvals, and the system tests only failing due to coverage (https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/449/pipeline/), I'll merge the PR

**Pull request merged**
