### PR TITLE
RD-5368: Revalidating variables and outputs after their import

### PR DESCRIPTION
**Pull request by NorbertAmartus**
## Description

Changes consists of reusing validating functions while importing variables and outputs from terraform module.
Futher refactor was not made as there is a [dedicated ticket](https://cloudifysource.atlassian.net/browse/RD-5332) for that

## Screenshots / Videos

N/A

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests

 

[Build Status](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3305/)

## Documentation

N/A

## Changes should be a part of 6.4.0 release?
Yes, corresponding PR with cherrypick will be created 🚀

### CODE REVIEW

**Review by qooban — COMMENTED** [review]
Don't have any comments to the code, looks good 👍🏻 

Tested the UI (followed steps to reproduce from RD-5368) and found out that after changing "TF module source" the errors in "TF variables and outputs mapping" section are not always cleared. It seems that  "TF module folder" is not always set after changing "TF module source". Is it related? Can we do something with it? 


https://user-images.githubusercontent.com/5202105/182368620-5e9e1c25-715e-4483-8661-4710ff5d2f0a.mp4

**Comment by NorbertAmartus** [comment]
> Don't have any comments to the code, looks good 👍🏻
> 
> Tested the UI (followed steps to reproduce from [RD-5368](https://cloudifysource.atlassian.net/browse/RD-5368)) and found out that after changing "TF module source" the errors in "TF variables and outputs mapping" section are not always cleared. It seems that "TF module folder" is not always set after changing "TF module source". Is it related? Can we do something with it?

@qooban 
### Ad 1. - "TF variables and outputs mapping" section are not always cleared
Current issue is consisting of errors that are not being reevaluated after importing `variables`/`outputs`
Having that in mind, clearing sections after changing "TF module source" seems to be a brand new functionality, which shouldn't be implemented as part of the [RD-5368](https://cloudifysource.atlassian.net/browse/RD-5368)

Nonetheless, it may be a nice idea, which could be discussed with PM 💪 

### Ad 2. - "TF module folder" is not always set after changing "TF module source".
It is not related, as currently we can open [staging env](https://staging.trn.cloudify.co/console/page/blueprints) and try to upload the following URL (which you've presented on video)
> https://github.com/MichaelShn/tf_testing_cert.git

When the URL would be provided, TF module folder still wouldn't be selected by default.
So that behavior is related to the current mechanism of selecting a default terraform module (it seems to be coded [here](https://github.com/cloudify-cosmo/cloudify-stage/blob/44224e38ad08019d72bcf27a97453648ee99f798/widgets/common/src/terraformModal/TerraformModal.tsx#L582-L589))

The question that my arise is: if that mechanism is working properly?
But that's a discussion which should be taken on a dedicated occasion 😁 

### Footer 😁 

I hope that I've addressed your questions 🎉 
If something would need more elaboration, let me know 🚀

**Comment by qooban** [comment]
> ### Ad 1. - "TF variables and outputs mapping" section are not always cleared
> Current issue is consisting of errors that are not being reevaluated after importing `variables`/`outputs` Having that in mind, clearing sections after changing "TF module source" seems to be a brand new functionality, which shouldn't be implemented as part of the [RD-5368](https://cloudifysource.atlassian.net/browse/RD-5368)

I think there's misunderstanding. I wrote:
> the errors in "TF variables and outputs mapping" section are not always cleared
not section itself.

I suspect that clearing error after changing TF module source and/or TF module folder should be done.
However, I'm not sure if that's in the scope of RD-5368 (IMHO it should be). Having solution for p. 2 would probably help in clearing errors as well.

To sum it up: Could you please check it with @MichaelShn ?

> ### Ad 2. - "TF module folder" is not always set after changing "TF module source".
> The question that my arise is: if that mechanism is working properly? But that's a discussion which should be taken on a dedicated occasion

Yeah, that might be solved within different ticket, but I guess @MichaelShn should be notified and possibly we should have a ticket for that.

**Comment by NorbertAmartus** [comment]
Sure, I'll sync with him on that topics 💪

**Comment by NorbertAmartus** [comment]
@qooban 

### Ad. 1 - Errors are not always cleared
I've discussed it with @MichaelShn and the outcome is that we want the user to be explicit about some operations (e.g. operations on `variables` and `outputs`) that's why we only want to revalidate specific parts of form on user declaration (in our case, on submitting the confirmation modal)

Because of that, mechanism implemented within this ticket is working properly and we don't need to worry about validating `variables`/`outputs` while providing another terraform module path 🎉


### Ad. 2 -  "TF module folder" is not always set after changing "TF module source".
It seems that the functionality is not working properly (so it's worth to say once more: nice catch! 😎 🎉 )
Previously linked [implementation of module selecting mechanism](https://github.com/cloudify-cosmo/cloudify-stage/blob/0516f765bb60b1d274728cc9b4cb7a7c2ac71052/widgets/common/src/terraformModal/TerraformModal.tsx#L582-L589) will be modified, so that the first available module will be selected as default 🎉 
(currently the first module containing phrase `terraform` or `tf` is being selected)

Corresponding ticket will be created for that adjustment 💪

**Review by qooban — APPROVED** [review]
Thanks for additional effort on clarifications.

**Pull request merged**
