### PR TITLE
RD-2917 Bumped cloudify-ui-common version

### PR DESCRIPTION
**Pull request by kubama**
## Description
Bumped cloudify-ui-common version to use fixed `getLogger` implementation.

## Screenshots / Videos
N/A

## Checklist

- [X] My code follows the UI Code Style.
- [x] I verified that all tests and checks have passed.
- [X] I verified if that change requires a documentation update.
- [X] I added proper labels to this PR.

## Tests
N/A

## Documentation
N/A

### CODE REVIEW

**Comment by kubama** [comment]
Hmmm... I messed something with the branch. Just a moment 🙂.

**Comment by kubama** [comment]
Fixed, please review

**Review by qooban — APPROVED** [review]
LGTM 👍🏻 

Do you plan to update `cloudify-blueprint-composer` also?
I think we don't need to have that in Composer v6.2, but it'd be good to have it already available in `master`.

**Comment by kubama** [comment]
> Do you plan to update `cloudify-blueprint-composer` also?
> I think we don't need to have that in Composer v6.2, but it'd be good to have it already available in `master`.

I did a quick check and it looks like composer is not prone to the same issue as for each category it obtains logger exactly once. So I'm not planing an update there, as it wouldn't change anything.

**Pull request merged**
