### PR TITLE
RD-6660: Modify input selector

### PR DESCRIPTION
**Pull request by Vorbert-Kruk**
## Description

Seems like #2348 has reverted a need for the previous fix, which was implemented within #2347 
Because of that, within this PR I'm reverting changes introduced by #2347

## Screenshots / Videos

N/A

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests

 

[Build Status](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4193/)

## Documentation

N/A

### CODE REVIEW

**Comment by kubama** [comment]
https://github.com/cloudify-cosmo/cloudify-stage/pull/2348 doesn't contain any functional changes, how is it possible that it's affecting input/textarea thing?
Maybe it's kind of random/nondeterministic whether input or textarea is rendered?

**Comment by Vorbert-Kruk** [comment]
> https://github.com/cloudify-cosmo/cloudify-stage/pull/2348 doesn't contain any functional changes, how is it possible that it's affecting input/textarea thing?   

You're right,
Sorry, I've linked wrong PR, the correct one is #2349 

> Maybe it's kind of random/nondeterministic whether input or textarea is rendered?
I'll answer on slack, as you've asked a similar question 😁

**Comment by Vorbert-Kruk** [comment]
Just to be sure, that the fix is not temporary, I've executed system tests multiple times

1.
[Build Status](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4195/)

2.
[Build Status](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4196/)

3.
[Build Status](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4197/)

**Comment by Vorbert-Kruk** [comment]
@kubama if everything would be okay, feel free to merge this PR - we could help current UI Guardian by doing that
But if you'd have additional topics, which I'd need to address, I'll get back to them after my vacations 🚀

**Review by kubama — APPROVED** [review]

**Pull request merged**
