### PR TITLE
RD-1829 Update Resource Filter's README

### PR DESCRIPTION
**Pull request by Gelio**
Add a note about incompatibility with the Deployments View widget.
The change to the docs is made in https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1880. I will wait for that PR to be merged before trying to merge this one (the CI won't let me do otherwise :smile: ).

## Screenshots

image

Unfortunately, the link to the Deployments View widget is broken due to RD-2455 (already happens in the Deployments View widget).

## System tests

I do not plan on running system tests, as it's an automated readme change that is validated in the multibranch pipeline :slightly_smiling_face:

### CODE REVIEW

**Comment by Gelio** [comment]
Doc tests failed as expected, because https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1880 is not merged yet

**Review by qooban — APPROVED** [review]
All good 👍🏻 Somewhere in the future we will need to fix RD-2455. 

Hopefully you'll be able to merge it next week after Ofer approves the change in the docs.

**Comment by Gelio** [comment]
Thanks for the approval :+1: 

> Somewhere in the future we will need to fix [RD-2455](https://cloudifysource.atlassian.net/browse/RD-2455).

Yeah, I was thinking about doing that now, but ended up deciding that it may not be as pressing. I asked Ofer and Alex in the comments what to do with RD-2455, maybe it will be done for 6.1 in the end :slightly_smiling_face:

**Comment by Gelio** [comment]
It turns out that I need to merge the docs changes to `6.0.0-build` branch too. I'm waiting for https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1881 to be merged

**Comment by Gelio** [comment]
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1881 is merged. Thus, I am merging this PR. I assume that the changes will ultimately land in the `6.1.0-branch` thanks to RD-2647

**Pull request merged**
