### PR TITLE
NE-5433 Adjusted tests scenario for system test failure

### PR DESCRIPTION
**Pull request by jyoti-siddareddi**
## Checklist

- [ ] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [ ] I added proper labels to this PR.

## Tests
Last nightly build:
https://jenkins.cloudify.co/job/Stage-UI-System-Test/5448/ where edit_spec was one of the failure due to isolated vm changes.
fixed them and here is the build of this branch https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/5450/pipeline

### CODE REVIEW

**Comment by jyoti-siddareddi** [comment]
Hi @qooban As discussed on the group chat earlier here is the adjustment on the error messages which were required in after the vm2 replacement with isolated vm. we have updated the same and verified the changes and build along with @Vorbert-Kruk .Thanks @Vorbert-Kruk for helping us fix this and validate the same.

**Review by qooban — COMMENTED** [review]
Can we adjust example widgets' archive filenames (`ModuleNotAllowed`, `ModuleNotAllowedInService`) so that they are more accurate (and indicate broken parts)?

**Comment by Vorbert-Kruk** [comment]
> Can we adjust example widgets' archive filenames (`ModuleNotAllowed`, `ModuleNotAllowedInService`) so that they are more accurate (and indicate broken parts)?

@qooban As @jyoti-siddareddi is not available today and during next week there is a public holiday in SGP, I'll try to assist with this one, to accelerate the process 👍 

Hope @jyoti-siddareddi that you wouldn't mind :)

**Comment by Vorbert-Kruk** [comment]
> Can we adjust example widgets' archive filenames (`ModuleNotAllowed`, `ModuleNotAllowedInService`) so that they are more accurate (and indicate broken parts)?

Files names were adjusted 👍 
File sizes may differ, but no major changes were done to them - just adjusted root directory name to match the new directory's name

**Review by qooban — APPROVED** [review]

**Comment by jyoti-siddareddi** [comment]
@Vorbert-Kruk  Thank you for taking this up while we were unavailable. :)

**Comment by Vorbert-Kruk** [comment]
> @Vorbert-Kruk Thank you for taking this up while we were unavailable. :)

No worries, I was happy to assist :)

**Pull request merged**
