### PR TITLE
RD-2149 Use is_not filter operator when drilling to subservices

### PR DESCRIPTION
**Pull request by Gelio**
With https://github.com/cloudify-cosmo/cloudify-manager/pull/2965, the UI can now use the new `is_not` filter rule operator that correctly includes all services, even those that do not have an `csys-obj-type` label.

Requires the latest 6.0 manager build to work. Otherwise, you may get errors related to the new operator being unknown, as I did when running the tests:
image

Yesterday's (2021-04-29) 6.0 manager build failed (see Slack for more information), we need to wait till the next successful build to verify it. I'll be on holiday next week, so I hope one of you can take over the PR and merge it :slightly_smiling_face: 

The rule for drilling down to subservices is now the same as in the system filter for services https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1144

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/538/pipeline

Ran 2021-04-30 13:15 CEST

### CODE REVIEW

**Review by kubama — APPROVED** [review]

**Review by qooban — APPROVED** [review]

**Comment by Gelio** [comment]
Thanks for reviews :+1: The previous system tests failed, probably since they were still using the old manager. A new version is available now, so here's another rerun:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/537/pipeline

**Comment by Gelio** [comment]
It turns out I have used the wrong operator. It should be `is_not` instead of `not_in`.

The drill-down tests now pass for me locally:

image

A run of system tests for `deployments_view_spec`:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/537/pipeline

**Review by kubama — APPROVED** [review]

**Review by qooban — APPROVED** [review]

**Comment by Gelio** [comment]
Hooray! An EOFException!

Here's a rerun:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/538/pipeline

**Comment by Gelio** [comment]
All the `deployments_view_spec` tests passed, so I'll merge the PR. IMO it does not affect other places in the app, so it's safe enough to merge without a full system tests run

**Pull request merged**
