### PR TITLE
RD-3069 Update documentation for Blueprint flow changes (#1613)

### PR DESCRIPTION
**Pull request by stepek**
Cherry pick of 2edafb93bde00891256d32333c5b7fe65cc1b789

### CODE REVIEW

**Review by qooban — COMMENTED** [review]
You need to update official documentation first on `6.2.0-build` branch.

**Comment by stepek** [comment]
@qooban please review it https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1961

**Comment by qooban** [comment]
> @qooban please review it [cloudify-cosmo/docs.getcloudify.org#1961](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1961)

Approved and merged. I have replayed the job in the CI to make it mergable.

**Review by qooban — APPROVED** [review]

**Comment by stepek** [comment]
@qooban Thanks

**Pull request merged**
