### PR TITLE
RD-1822 Keep deployment selection after executing workflows

### PR DESCRIPTION
**Pull request by Gelio**
This PR fixes the selection of deployments in the Deployments View widget. It builds on #1267.

Previously, the selection was set to `null` after executing a workflow. This happened because:
1. The `deployments:refresh` event was triggered without any arguments
2. The Resource Filter widget was listening on that event and when it fired, it set the `deploymentId` to whatever was the argument of the event

    https://github.com/cloudify-cosmo/cloudify-stage/blob/6514122edaad401b6b0592c770a287b95f206844/widgets/filter/src/Filter.jsx#L79-L85

    Since the argument was `undefined`, `deploymentId` in that function was set to the default `null` value.

Adding the `deploymentId` preserves the selection when executing workflows.

The problem only happens when the Resource Filter widget is present on the same page (e.g. in tests).

## Video

https://user-images.githubusercontent.com/889383/112172092-b206c000-8bf4-11eb-8864-3f2d883b7990.mp4

Notice that the right pane was kept as-is, and was not reset to the "unknown selection" state.

## System tests

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/339/pipeline

Ran 2021-03-26 11:44 CET

### CODE REVIEW

**Review by kubama — DISMISSED** [review]

**Comment by Gelio** [comment]
I've rebased the PR to resolve merge conflicts.

**Review by qooban — APPROVED** [review]

**Comment by Gelio** [comment]
I've rebased my tree of branches after #1254 was merged

**Comment by Gelio** [comment]
I've rebased my tree of branches after #1265 was merged

Still, #1267 needs to be merged first before this one

**Comment by Gelio** [comment]
I've rebased the PR on `master`, ready to be merged. Queued up system tests:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/334/pipeline/

I'm looking for reapprovals slightly_smiling_face

**Review by qooban — DISMISSED** [review]

**Review by kubama — APPROVED** [review]

**Comment by Gelio** [comment]
[Previous system tests](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/334/pipeline) failed with an `InterruptedException` :slightly_frowning_face: 

Here's a new run:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/337/pipeline

**Comment by Gelio** [comment]
The tests for `deployment_actions_spec` were stateful - one of them relied on the deployment filter being cleared in the previous one (which did not happen, since running an execution will preserve the deployment to be filtered now).

I've fixed that in the latest commit. Here are the system tests:

https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/339/pipeline

**Review by qooban — APPROVED** [review]

**Pull request merged**
