### PR TITLE
RD-1457 Remove `managerIp` column from UserApps table

### PR DESCRIPTION
**Pull request by qooban**

### CODE REVIEW

**Comment by qooban** [comment]
@kubama @Gelio 
The PR is not yet finalized, but if you can take a look, feel free. I expect only some test additions, no changes in the source code planned.

I personally don't feel strong in the migrations and it happened few times that there were problems in the customer environment because of those migrations. That's why I'm considering adding more tests here, but I don't know if I'll manage to do that on time. 

Do you have any suggestions what kind of tests we should have here? 
Maybe a test comparing only `UserApps` table changes (before the migration and after the migration)?

**Comment by Gelio** [comment]
I'll review the PR when I have some free time after all the 6.0 stuff :smile: (probably next week)

**Comment by qooban** [comment]
@alexmolev @ofercloudify 
Hmm... I'm wondering right now... Maybe we can postpone RD-1457 to 6.1? What do you think?

It's quite risky IMHO. As I mentioned previously - we already had issues with migrations before. And doing such change at the last phase just before the release? Maybe not the best what we can do.

**Comment by ofercloudify** [comment]
@alexmolev After discussing this with @qooban , seeing that the major risks relate to upgrading, and upgrade to 6.0 is not officially supported, we can push this in  and set a task to monitor the upgrade for this in 6.1

**Comment by qooban** [comment]
@ofercloudify Thanks. Created RD-2408 to handle deeper testing.

**Comment by qooban** [comment]
@kubama @Gelio It's ready for review, then. I'll not add more tests for 6.0 release. See discussion above.

**Review by kubama — APPROVED** [review]

**Comment by Gelio** [comment]
I'll take a look tomorrow or on Monday, as I still need to attend to https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1840 and https://github.com/cloudify-cosmo/cloudify-stage/pull/1385. I believe you could merge with just 1 approval if we're short on time :slightly_smiling_face:

**Review by Gelio — APPROVED** [review]
Actually, I just skimmed the PR really fast, did not find anything concerning, but my confidence if very low :smile: I did not do any testing

**Comment by qooban** [comment]
System tests execution scheduled: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/624/
Once it passes (maybe I'm expecting too much ;-)), I'm going to merge this PR.

**Comment by qooban** [comment]
Yes, I'm of course expecting too much 🙂 

https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/624/ failed due to:
```
15:34:49  Cannot contact stage-ui-system-test-624-9kxcl-67jkj-p7tfl: java.lang.InterruptedException
Pod jenkins/stage-ui-system-test-624-9kxcl-67jkj-p7tfl was just deleted
```

**Comment by qooban** [comment]
I'll try one more time: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/631

**Comment by qooban** [comment]
I reached
```
11:12:37    Running:  widgets/user_defined_widgets_spec.ts                                          (51 of 53)
11:13:07  Cannot contact stage-ui-system-test-631-zclvq-jv4rn-vqqtf: java.lang.InterruptedException
11:24:30  Could not connect to stage-ui-system-test-631-zclvq-jv4rn-vqqtf to send interrupt signal to process
```
so it's not bad looking at our recent stats.

Discovered one failure in`tours_spec` (related to my recent merge - https://github.com/cloudify-cosmo/cloudify-stage/pull/1384). It is already fixed in https://github.com/cloudify-cosmo/cloudify-stage/pull/1377 .

I'm going to merge this PR once CI passes.

**Pull request merged**
