### PR TITLE
RD-1212 Remove unused Jenkinsfile

### PR DESCRIPTION
**Pull request by Gelio**
This repository has 2 Jenkinsfiles:

1. https://github.com/cloudify-cosmo/cloudify-stage/blob/master/jenkins/Jenkinsfile
2. https://github.com/cloudify-cosmo/cloudify-stage/blob/master/Jenkinsfile

It seems that the latter one is unused, and thus, can be removed to avoid confusion.

### CODE REVIEW

**Review by qooban — CHANGES_REQUESTED** [review]
This is just one specific thing. I would prefer to first group all the actions necessary for the clean-up. 

We still have old CircleCI configuration in all repos, which is not used.
We still have duplicated Jenkinsfiles in stage and composer.
When I was tracking Jenkins migration I spotted also the following: https://cloudifysource.atlassian.net/browse/RD-269

IMHO most of these things should be first discussed, planned and then implemented.
Changing one specific thing in one repo will only introduce more confusion.

**Comment by Gelio** [comment]
@qooban Sure, I was not aware of such larger preexisting issues :slightly_smiling_face: 

1. I can close this PR and move https://cloudifysource.atlassian.net/browse/RD-1212 to the story you referred to. I will also update the RD-1212 ticket with items to clean up (cleaning up Jenkinsfiles and CircleCI config in both stage and composer). Is that ok?
2. Do we have some priority for that story already set? Having such duplications as technical debt can only cause confusion, as it caused for me :slightly_smiling_face: Especially if such issues are not explained to newcomers early on

**Comment by qooban** [comment]
@Gelio 

> 1. I can close this PR and move https://cloudifysource.atlassian.net/browse/RD-1212 to the story you referred to. I will also update the RD-1212 ticket with items to clean up (cleaning up Jenkinsfiles and CircleCI config in both stage and composer). Is that ok?

Yep, thanks, you can update and move that ticket to the story I referred to.

> 2. Do we have some priority for that story already set? Having such duplications as technical debt can only cause confusion, as it caused for me :slightly_smiling_face: Especially if such issues are not explained to newcomers early on

:-) That's question to Igor, I think, as he was responsible for migration from CircleCI and old Jenkins to new Jenkins.
@warolv : Do you have a plan for cleaning-up our repositories after migration from CircleCI to Jenkins? (old Jenkins files and CircleCI configuration) I remember that you blocked me from removing all those leftovers, because you still used it. What is the status and plan right now?

**Comment by Gelio** [comment]
@qooban I've added more information to https://cloudifysource.atlassian.net/browse/RD-1212 description and moved it under RD-269. I'm closing the PR, since it's no longer relevant :slightly_smiling_face: but the discussion can still continue

**Comment by warolv** [comment]
> @Gelio
> 
> > 1. I can close this PR and move https://cloudifysource.atlassian.net/browse/RD-1212 to the story you referred to. I will also update the RD-1212 ticket with items to clean up (cleaning up Jenkinsfiles and CircleCI config in both stage and composer). Is that ok?
> 
> Yep, thanks, you can update and move that ticket to the story I referred to.
> 
> > 1. Do we have some priority for that story already set? Having such duplications as technical debt can only cause confusion, as it caused for me 🙂 Especially if such issues are not explained to newcomers early on
> 
> :-) That's question to Igor, I think, as he was responsible for migration from CircleCI and old Jenkins to new Jenkins.
> @warolv : Do you have a plan for cleaning-up our repositories after migration from CircleCI to Jenkins? (old Jenkins files and CircleCI configuration) I remember that you blocked me from removing all those leftovers, because you still used it. What is the status and plan right now?

@Gelio @qooban, the answer is yes we can already remove those files, you can remove it by yourself or open please ticket on me or @yuvlar, we will do it.

**Comment by qooban** [comment]
@warolv The ticket related to that specific change (old Jenkins and CircleCI configurations removal) was created by @Gelio : https://cloudifysource.atlassian.net/browse/RD-1212 . It is part of more general ticket containing leftovers I spotted when you did the migration: https://cloudifysource.atlassian.net/browse/RD-269 . Maybe some of them has already been solved, please review. As we're quite loaded, I'd like to leave those tickets to you. Just let us know when it would be possible to have it implemented.

**Pull request closed without merging**
