### PR TITLE
RD-2430 Add secrets to OpenStackV3 in GettingStartedModal

### PR DESCRIPTION
**Pull request by leon-good-life**
## Description
Jira ticket: https://cloudifysource.atlassian.net/browse/RD-2430

## Screenshots / Videos
Screen Shot 2022-07-26 at 11 51 21
Screen Shot 2022-07-26 at 11 50 40
Screen Shot 2022-07-26 at 11 51 03

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
I started `getting_started_spec` in Jenkins: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3219/pipeline

 

## Documentation
I checked. There is no screenshot to update.
https://docs.cloudify.co/latest/working_with/console/getting-started/
https://docs.cloudify.co/latest/working_with/console/getting-started/navigation/

### CODE REVIEW

**Comment by leon-good-life** [comment]
I started `getting_started_spec` in Jenkins: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3219/pipeline

**Review by kubama — APPROVED** [review]

**Review by qooban — CHANGES_REQUESTED** [review]
@leon-good-life Please wait with it. Which issues this PR is solving? There are couple of them mentioned in RD-2430 comments, e.g. there supposed to be more secrets added which I don't see in the PR.

**Comment by leon-good-life** [comment]
Yesterday Alex was sitting with me, and we worked on this ticket. 

He told me that I need to add 3 secrets:
- openstack_region 
- openstack_project_domain_name
- openstack_user_domain_name
The issue of other secrets is because wrong blueprint, which is not a frontend bug. Alex opened a separate ticket for it.

I asked Alex how can I check that my changes actually work, and he told me to look at:
180965651-66716c67-9571-48b8-b6fa-606d3a1e08f7

**Comment by leon-good-life** [comment]
Alex told me right now that he fixed the other error.
I will check now again.

**Comment by leon-good-life** [comment]
It works without errors:
Screen Shot 2022-08-02 at 11 46 46

**Review by qooban — CHANGES_REQUESTED** [review]
Did quick UI test and for OpenStack blueprints it's still not fully working. It's possible to deploy `OpenStack-Basics-Simple-Service-Setup` without secrets error, but when deploying `OpenStack-Basics-VM-Setup` user gets:
image

so the issue I described in [this comment](https://cloudifysource.atlassian.net/browse/RD-2430?focusedCommentId=76810) is still not solved.

CC: @alexmolev

**Review by qooban — APPROVED** [review]
As discussed during today's daily, @alexmolev accepted the current solution, so I'm approving this PR.

**Pull request merged**
