### PR TITLE
RD-3974: Fix the intercepted request for tenants tests

### PR DESCRIPTION
**Pull request by NorbertAmartus**
## Description

I've found out, that the interception wasn't working at all   
I quickly discovered, that the problem is related to the incorrect URL (I've must done a typo, while addressing the [PR comments](https://github.com/cloudify-cosmo/cloudify-stage/pull/1740#discussion_r784729778))    
This problem has been fixed, by adding `/` before `console/sp/tenants` address 😉 

## Screenshots / Videos

N/A

## Checklist

- [x] My code follows the UI Code Style.
- [ ] I verified that all tests and checks have passed.
- [ ] I verified if that change requires a documentation update.
- [x] I added proper labels to this PR.

## Tests

 

[System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1826) (only regarding test file on which I was working on) has been executed 🚀
Currently in progress ⏰

## Documentation

N/A

### CODE REVIEW

**Review by qooban — APPROVED** [review]
Thanks for quick re-action. 

I'm wondering if that 250ms won't be too short in slower environments, but if you see that it works then, I'm OK with merging this change.

Suggestion for the future - in cases where there might be flakiness experienced in a specific system test - I'm usually running that specific test multiple times (e.g. 3 times) to have better overview.

**Comment by qooban** [comment]
@NorbertAmartus Seems like one of our Cypress component tests is failing - see [Stage-UI-System-Test/1826](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1826) :
`app/sidebar/TenantSelection_spec.tsx`. Please check locally. It was probably "covered by" system tests failing as components tests are not executed when system tests are failing.

**Comment by NorbertAmartus** [comment]
> @NorbertAmartus Seems like one of our Cypress component tests is failing - see [Stage-UI-System-Test/1826](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1826) : `app/sidebar/TenantSelection_spec.tsx`. Please check locally. It was probably "covered by" system tests failing as components tests are not executed when system tests are failing.

Locally is failing too.
I'll do a further investigation on that manner

**Comment by NorbertAmartus** [comment]
As discussed on the slack, I'll merge this PR and create a seperate one for the problems related to the `TenantSelection_spec.tsx`

**Pull request merged**
